version: "3.8"
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: node app.js
    links:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      DEBUG: nodejs-docker-express:*
  mongodb:
    image: mongo:bionic

    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:

  # mysql_server:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     - MYSQL_DATABASE=test_db
  #     - MYSQL_USER=dan
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_ROOT_PASSWORD=secret
