version: "3.8"
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    links:
      - mongodb
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
  mongodb:
    image: mongo:bionic
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
